### ISSUE TITLE
Stopped working in Sierra

### ISSUE THREAD

**Issue by firedev** [alexchiri/format-sql-alfred-workflow#1]
Hi, formatSql stopped working in Sierra, here is a Sample log. Any ideas?

```
E, [2016-10-10 16:34:24 #56032] ERROR -- com.alexchiri.alfred2-format-sql-ruby: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<JSON::ParserError: 757: unexpected token at '<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.6.2 (Ubuntu)</center>
</body>
</html>
'>
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'  
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'  
./main.rb:41:in `block in <main>'  
/Users/pain/Dropbox/Library/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AA9F76F1-6373-4C75-BE5F-49319924B5E4/bundle/ruby/2.0.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'  
./main.rb:15:in `<main>'
```

**Comment by alexchiri** [comment]
@firedev I'll check it out soon. Seems like something related to the SQLFormat API it uses.

**Comment by alexchiri** [comment]
@firedev fixed it! the service enforced now HTTPS, therefore returned a 301 for HTTP. Pushed a new version which contains the fix. Let me know if it works for you as well.

**Comment by firedev** [comment]
Thanks! Works fine.
